return {
	-- "nvim-neo-tree/neo-tree.nvim",
	-- version = "*",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	{ "nvim-tree/nvim-web-devicons", lazy = false, enabled = true }, -- not strictly required, but recommended
	-- 	"MunifTanjim/nui.nvim",
	-- },
	-- cmd = "Neotree",
	-- keys = {
	-- 	{ "\\", ":Neotree reveal<CR>", desc = "NeoTree reveal", silent = true },
	-- },
	-- opts = {
	-- 	filesystem = {
	-- 		window = {
	-- 			mappings = {
	-- 				["\\"] = "close_window",
	-- 			},
	-- 		},
	-- 	},
	-- },
}
